spring:
  profiles.active: local

---
logging:
  path: /var/log
  file: example-app.log
spring:
  main:
    show_banner: false
  profiles: local
  application:
    name: Example App
    description: This is an example cross store app
  management:
    port: 8081
    security:
      enabled: false
  datasource:
    name: PostgreSQL 
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/crossstore
    username: crossstore
    password: crossstore
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: 'create-drop'
        temp:
          use_jdbc_metadata_defaults: false
---
spring:
  profiles: dev
---
spring:
  profiles: qa
---
spring:
  profiles: stage
---
spring:
  profiles: prod